image: golang:1.16

stages:
  - build
  - deploy

variables:
  EB_ENVIRONMENT_NAME: "GoGitLab-env"
  EB_APPLICATION_NAME: "GoGitLab"
  AWS_DEFAULT_REGION: "us-east-1"

before_script:
  - apt-get update -y
  - apt-get install zip -y
  - go get -v github.com/aws/aws-sdk-go/...

build:
  stage: build
  script:
    - go build -o myapp

deploy:
  stage: deploy
  script:
    - zip -r myapp.zip . -i myapp
    - apt-get install -y awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.region $AWS_DEFAULT_REGION
    - aws configure set default.output json
    - aws s3 cp myapp.zip s3://go-app-bucket/myapp.zip
    - aws elasticbeanstalk create-application-version --application-name $EB_APPLICATION_NAME --version-label $CI_COMMIT_SHORT_SHA --source-bundle S3Bucket="go-app-bucket",S3Key=myapp.zip
    - aws elasticbeanstalk update-environment --environment-name $EB_ENVIRONMENT_NAME --version-label $CI_COMMIT_SHORT_SHA
